### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by kevon217** [Mintplex-Labs/vector-admin#25]
In your README, it says the setup procedure will not work on Windows. Does that mean this only works on Mac OS for now?

**Comment by timothycarambat** [comment]
It will only work on Windows when you run in docker. If you try to spin this up in development mode on your host machine you will likely run into issues setting up Python and such. You absolutely can run this in Windows but that text in the Readme is present so that the issue log isn't just a bunch of issue with Windows users trying to run it and having permission/install/WSL issues that arent core to the product.

You are absolutely welcome to run it locally on Windows, its just untested.

**Comment by kevon217** [comment]
good to hear. thanks for the quick reply!
