### ISSUE TITLE
Vectors without a namespace

### ISSUE THREAD

**Issue by ayso-ai** [Mintplex-Labs/vector-admin#27]
VectorAdmin not pulling data from Pinecone for vectors without a namespace. Is that a known issue or am I missing something?

**Comment by timothycarambat** [comment]
It currently does not support non-namespaced vectors. This is something that **can** be supported, but likely will cause complications as the name in pinecone for "no namespace" is just `""` which will cause issues on the DB side of handling this.

Are you just querying on a specific metadata across all your vectors instead of namespacing? Or is this specific to your use case?

**Comment by ayso-ai** [comment]
I'm using Flowise to upsert documents to Pinecone and it looks like it does
so without using namespaces. Not sure about a workaround here...

**Comment by timothycarambat** [comment]
It's good practice to partition the data into namespaces. Flowise does support this! You just need to define it so it is used during execution.

<img width="449" alt="Screen Shot 2023-08-08 at 1 03 36 PM" src="https://github.com/Mintplex-Labs/vector-admin/assets/16845892/c6c9dead-300a-4a79-90bc-193c2d2c9904">
<img width="691" alt="Screen Shot 2023-08-08 at 1 03 41 PM" src="https://github.com/Mintplex-Labs/vector-admin/assets/16845892/949f4193-05ba-42a1-91b2-1862b025509c">
